### ISSUE TITLE
Incorrect platform provisioning profile

### ISSUE THREAD

**Issue by yonaskolb** [bitrise-steplib/steps-ios-auto-provision#23] opened 2018-04-06 13:15 UTC
If there are multiple provisioning profiles with the same bundleID (for example for iOS and tvOS), the auto provision step sometimes downloads the incorrect provisioning profile. This causes signing to fail later. It should check the type for the correct platform

Here you can see it downloads the correct development profile, but incorrect distribution profile:
```
Analyzing project
project codesign identity: iPhone Developer
project team id: 3PU2FX2MA5
uses xcode managed signing: true
target #0: Axis_iOS (co.massive.axis.demo) with 0 services
Matching project codesign identity with the uploaded certificates
using: iPhone Developer: Yonas Kolb (XY7TEP9H45) [2904252714206315985]
using: iPhone Distribution: Massive Interactive Pty Ltd (3PU2FX2MA5) [9139218735286723938]
Ensure Provisioning Profiles on Developer Portal
checking xcode managed development profile for target: Axis_iOS (co.massive.axis.demo) with 0 services on developer portal
downloading development profile: iOS Team Provisioning Profile: co.massive.axis.demo
checking xcode managed app-store profile for target: Axis_iOS (co.massive.axis.demo) with 0 services on developer portal
downloading app-store profile: tvOS Team Store Provisioning Profile: co.massive.axis.demo
```

This then creates an error in the Xcode Archive step
```
error: exportArchive: No "iOS App Store" profiles for team '3PU2FX2MA5' matching 'tvOS Team Store Provisioning Profile: co.massive.axis.demo' are installed.
```

**Comment by viktorbenei** [comment] 2018-04-10 16:24
Thanks for reporting @yonaskolb , we'll fix this ASAP! :)

**Comment by godrei** [comment] 2018-04-24 10:34
Hi @yonaskolb ,
we released a new version ([1.0.2](https://github.com/bitrise-steplib/steps-ios-auto-provision/releases/tag/1.0.2)), which fixes this issue.

I'll close this issue, but if you need more info/help just let us know and we'll reopen it!

**Comment by yonaskolb** [comment] 2018-04-24 11:28
Fantastic, thanks guys! 🎉

**Comment by viktorbenei** [comment] 2018-04-28 15:38
Thanks for reporting @yonaskolb ! ;)

**Comment by wangqingzhouleo** [comment] 2018-07-02 07:02
Hey guys, I'm using version 1.1.3 but still have some issues with auto provision step when setting `generate_profiles` to yes.

The first issue is about duplicated provisioning profile name: In my repository, both iOS and tvOS targets are sharing the same code base, so both of them are having the same bundle identifier. iOS auto provisioning work fine, but when I generating profiles for tvOS, it fails due to duplicated provisioning profile name. Maybe we could have another configuration for provisioning profile name?

The second issue is about incorrect platform provisioning profile which generated by auto provision step. This step always generates iOS Development or iOS Distribution profiles. Is there a way to generate tvOS profiles in this step (maybe it's better to have a different name so it solves previous issue)?

**Comment by trapacska** [comment] 2018-07-04 14:50
Hey @wangqingzhouleo !

Thanks for reporting. Just scheduled to check+fix it. When it has some progress we'll notify you here.

**Comment by wangqingzhouleo** [comment] 2018-08-15 00:13
Hi @trapacska, any progress for this issue?

**Comment by trapacska** [comment] 2018-08-23 07:46
@wangqingzhouleo still not there. Sorry about that. Will try our best 🙂

**Comment by trapacska** [comment] 2018-11-08 11:47
The new release is out, please let us know if the issue is still persist.

https://github.com/bitrise-steplib/steps-ios-auto-provision/releases/1.2.1

**Comment by wangqingzhouleo** [comment] 2019-01-08 00:34
Hi @trapacska,
Thanks for the fix! It can generate profiles for correct platform!
However, just noticed another minor issue for this step: it does not describe the platform in profile name.
Currently I have 2 Bitrise projects using the same bundle ID, one for iOS and one for tvOS. Both of them sharing the same app in iTunes Connect. When I trying to use auto generate profile for both projects, it only generates profile for the project which builds first. The later project will encounter an error `Multiple profiles found with the name xxx. Please remove the duplicate profiles and try again `.

Shall we add platform in the profile name?

Many thanks,

**Comment by lpusok** [comment] 2019-04-03 14:02
Hi @wangqingzhouleo,
Thanks for the report, created an internal bug ticket.

**Comment by emirandm** [comment] 2019-12-03 11:27
@lpusok Do you have an update on this issue?

**Comment by Roland-Bak** [comment] 2020-01-02 13:23
Hi there @emirandm!

Just wanted to update you that this is still on the way, but once we are done with the finishing touches, we'll let you know! 😉

**Comment by lszucs** [comment] 2020-02-13 15:49
Hi @yonaskolb,

CC: @wqz-leo @emirandm 

This issue should be resolved by now, please try the latest step release if the issue still persists in your builds.

@emirandm: thanks for the contribution! :)

I will be closing this issue in a few days, if no objections.

**Closed** 2020-02-13 15:50 UTC
Labels: bug
