### ISSUE TITLE
Error: Can't find class 'adhoc'

### ISSUE THREAD

**Issue by marspzb** [bitrise-steplib/steps-ios-auto-provision#49] opened 2018-12-14 18:32 UTC
Hi while doing the auto-provisioning step I'm receiving this error, this was working some days ago but after updating a new provisioning profile I'm getting this error. Also we're using a developer profile in order to signin the project and we are not provisioning for adhoc.

Here is the stack trace of the error, tried with multiple versions and none of them worked:
generate_profiles set to true, but failed to generate Provisioning Profiles with error:
Can't find class 'adhoc'
Trying to use Xcode managed Provisioning Profiles
checking xcode managed development profile for target: TheTicketMaster (com.scrnz.theticket) with 1 services on developer portal
Error:
Can't find class 'adhoc'
Stacktrace (for debugging):
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:207:in `factory'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:321:in `block in all'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:321:in `map!'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.102.0/spaceship/lib/spaceship/portal/provisioning_profile.rb:321:in `all'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise758575677/step_src/lib/autoprovision/portal/profile_client.rb:137:in `block in fetch_profiles'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise758575677/step_src/lib/autoprovision/portal/common.rb:10:in `run_and_handle_portal_function'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise758575677/step_src/lib/autoprovision/portal/profile_client.rb:137:in `fetch_profiles'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise758575677/step_src/lib/autoprovision/portal/profile_client.rb:11:in `ensure_xcode_managed_profile'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise758575677/step_src/lib/autoprovision/profile_helper.rb:65:in `block in ensure_xcode_managed_profiles'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise758575677/step_src/lib/autoprovision/profile_helper.rb:59:in `each'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise758575677/step_src/lib/autoprovision/profile_helper.rb:59:in `ensure_xcode_managed_profiles'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise758575677/step_src/lib/autoprovision/profile_helper.rb:40:in `block in ensure_profiles'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise758575677/step_src/lib/autoprovision/profile_helper.rb:38:in `each'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise758575677/step_src/lib/autoprovision/profile_helper.rb:38:in `ensure_profiles'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise758575677/step_src/lib/autoprovision/profile_helper.rb:32:in `rescue in ensure_profiles'
/private/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise758575677/step_src/lib/autoprovision/profile_helper.rb:25:in `ensure_profiles'
/var/folders/90/5stft2v13fb_m_gv3c8x9nwc0000gn/T/bitrise758575677/step_src/step.rb:89:in `<main>'

Thank you,

**Comment by andrewtheis** [comment] 2018-12-14 20:57
👍 Also receiving this error

**Comment by andrewtheis** [comment] 2018-12-14 22:47
This appears to be an issue fixed in the latest Fastlane version. https://github.com/fastlane/fastlane/pull/13907

**Comment by Diego-Franco** [comment] 2018-12-14 23:04
@andrewtheis so, this step need to update their fastlane? or we can do it in our side?

**Comment by jairomc** [comment] 2018-12-15 00:10
how can i update Fastlane for this step?

**Comment by tamasbazs** [comment] 2018-12-15 14:12
Hi @jairomc, @andrewtheis, @marspzb,
Thank you for reporting this issue! We have a PR to use the latest version of Fastlane to address the issue. We'll update you as soon as it's merged and the new step version is available to use!

**Comment by kleiberjp** [comment] 2018-12-17 19:59
@tamasbazs any update? there is anything we can do for use a stable version without this breakchange ?

**Comment by tamasbazs** [comment] 2018-12-17 20:33
Hi @kleiberjp, @jairomc, @andrewtheis, @marspzb,
Our tooling team is investigating an issue with the fix on our Xcode 10.0 stacks, but the other stacks should  be working fine.

There's also a temporary workaround you can use while the PR is merged. Basically you can run the build using the step from the fork by replacing the following line in the bitrise.yml:

ios-auto-provision:
with:

git::https://github.com/tamasbazs/steps-ios-auto-provision.git@master:

The lines that come after this specify the inputs and those can be left in the bitrise.yml  as the fork would also be able to use them.

If you'd decide to give this a try we'd strongly recommend to switch back to the original step after the PR is merged to be sure you don't miss out on any new features/fixes that come with the original step! 🙂

**Comment by barsumek** [comment] 2018-12-17 21:05
Hello @tamasbazs 

Thanks for the temporary workaround. 🥇  We have a problem with it though – our build is still failing with:
```
Error:
765: unexpected token at 'Bad Request'
Stacktrace (for debugging):
/usr/local/Cellar/ruby/2.5.3/lib/ruby/2.5.0/json/common.rb:156:in `parse'
/usr/local/Cellar/ruby/2.5.3/lib/ruby/2.5.0/json/common.rb:156:in `parse'
/usr/local/lib/ruby/gems/2.5.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/parse_json.rb:11:in `block in <class:ParseJson>'
/usr/local/lib/ruby/gems/2.5.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:51:in `parse'
/usr/local/lib/ruby/gems/2.5.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:40:in `process_response'
/usr/local/lib/ruby/gems/2.5.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:33:in `block in call'
/usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/response.rb:61:in `on_complete'
/usr/local/lib/ruby/gems/2.5.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response_middleware.rb:31:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
/usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
/usr/local/lib/ruby/gems/2.5.0/gems/faraday-0.15.4/lib/faraday/connection.rb:175:in `post'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.111.0/spaceship/lib/spaceship/client.rb:818:in `block in send_request'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.111.0/spaceship/lib/spaceship/client.rb:602:in `with_retry'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.111.0/spaceship/lib/spaceship/client.rb:817:in `send_request'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.111.0/spaceship/lib/spaceship/client.rb:669:in `request'
/usr/local/lib/ruby/gems/2.5.0/gems/fastlane-2.111.0/spaceship/lib/spaceship/portal/portal_client.rb:687:in `create_provisioning_profile!'
```

I am not that familiar with `fastlane` to guess what's the cause, but I found these two issues:
https://github.com/fastlane/fastlane/issues/13666
https://github.com/fastlane/fastlane/issues/13916 (last comments here are especially relevant)
Looks like there's an unnecessary hack in fastlane, which needs to be removed and merged to fix our builds, but if you happen to know another workaround then I'd greatly appreciate if you could let us know. 😃

**Comment by matteinn** [comment] 2018-12-18 13:30
@barsumek same issue here

**Comment by kleiberjp** [comment] 2018-12-18 20:58
HI @tamasbazs , I've implemented the fix recommended but, still having problems for install

**Comment by matteinn** [comment] 2018-12-19 10:38
There's an open PR here https://github.com/bitrise-steplib/steps-ios-auto-provision/pull/51

**Comment by godrei** [comment] 2018-12-19 16:49
Hi @marspzb ,
we released a new version of the step: https://github.com/bitrise-steplib/steps-ios-auto-provision/releases/tag/1.2.3 which fixes this issue.
I'll close this issue, but if you need more info/help please open a new issue!

**Closed by godrei** 2018-12-19 16:49 UTC
